### Approve PO
POST http://localhost:4004/odata/v4/po/approvePO
Content-Type: application/json

{
  "ID": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
}

### Generate PO Insight
POST http://localhost:4004/odata/v4/po/generatePOInsight
Content-Type: application/json

{
  "ID": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"
}